@extends('customer.layout.partial.master')
@section('title', 'Halaman Home')
@section('content')
@include('customer.content.home.HeroStart')
@include('customer.content.home.FeatursSection')
@include('customer.content.home.FruitsShop')
@include('customer.content.home.Featurs')
@include('customer.content.home.VesitableShop')
@include('customer.content.home.BannerSection')
@include('customer.content.home.BestsalerProduct')
@include('customer.content.home.Fact')
@include('customer.content.home.Tastimonial')
@endsection
